services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    #image: helpdesk
    container_name: helpdesk-app
    restart: unless-stopped
    #environment:
    #  - SITE_URL=http://localhost
    #ports:
    #  - 50080:80
    volumes:
      - app:/var/www
    networks:
      - helpdesk

  db:
    image: mariadb:latest
    container_name: helpdesk-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
    volumes:
    - ./db.sql:/docker-entrypoint-initdb.d/dump.sql
    networks:
      - helpdesk

  nginx:
    image: nginx:alpine
    container_name: helpdesk-nginx
    restart: unless-stopped
    ports:
      - 50080:80
    volumes:
      - app:/var/www
      - ./nginx:/etc/nginx/conf.d/
    networks:
      - helpdesk

networks:
  helpdesk:
    driver: bridge

volumes:
  app:
