services:
  app:
    build:
      args:
        user: helpdesk
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: helpdesk
    container_name: helpdesk-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - helpdesk

  db:
    image: mysql:5.6.25
    container_name: helpdesk-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'helpdesk'
      MYSQL_ROOT_PASSWORD: 'helpdesk'
      MYSQL_PASSWORD: 'helpdesk'
      MYSQL_USER: 'helpdesk'
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - 33061:3306
    networks:
      - helpdesk

  nginx:
    image: nginx:alpine
    container_name: helpdesk-nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./.docker/nginx:/etc/nginx/conf.d/
    networks:
      - helpdesk

networks:
  helpdesk:
    driver: bridge