services:
  app:
    build:
      args:
        user: helpdesk
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: helpdesk
    container_name: helpdesk-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - helpdesk

  db:
    build:
      args:
        user: ${MYSQL_USER}
        database: ${MYSQL_DATABASE}
        password: ${MYSQL_PASSWORD}
      context: ./
      dockerfile: ./.docker/mysql/Dockerfile
    image: mysql:latest
    container_name: helpdesk-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - 33061:3306
    networks:
      - helpdesk

  nginx:
    image: nginx:alpine
    container_name: helpdesk-nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./.docker/nginx:/etc/nginx/conf.d/
    networks:
      - helpdesk

networks:
  helpdesk:
    driver: bridge